# Generated by Django 6.0.4 on 2026-05-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='gst_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
