# Generated by Django 6.0.4 on 2026-05-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_party_gst_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='p_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_of_issue',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
