# Generated by Django 6.0.4 on 2026-05-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_invoiceitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
